[package]
name = "test-kd-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.0"
kd-tree = { version = "0.4.1", features = ["nalgebra"] }
